#!/usr/bin/env python3
"""
Analysis script for simulation convergence data.
Reads CSV files generated by simulation_convergence.py and creates plots
showing convergence behavior.
"""

import csv
import sys
import os
import matplotlib.pyplot as plt
import numpy as np
from typing import List, Tuple


def load_convergence_data(csv_file: str) -> Tuple[List[int], List[float], List[float]]:
    """
    Load convergence data from CSV file.

    Returns:
        simulations: List of simulation counts
        win_probs: List of win probabilities
        timestamps: List of timestamps
    """
    simulations = []
    win_probs = []
    timestamps = []

    with open(csv_file, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            simulations.append(int(row['simulations_run']))
            win_probs.append(float(row['win_probability']))
            timestamps.append(float(row['timestamp']))

    return simulations, win_probs, timestamps


def calculate_convergence_metrics(win_probs: List[float]) -> Tuple[List[float], List[float]]:
    """
    Calculate convergence metrics.

    Returns:
        differences: Absolute difference from final value at each point
        rolling_std: Rolling standard deviation of last N values
    """
    if len(win_probs) < 2:
        return [], []

    final_value = win_probs[-1]

    # Calculate absolute differences from final value
    differences = [abs(prob - final_value) for prob in win_probs]

    # Calculate rolling standard deviation (last 10 values)
    rolling_std = []
    window_size = min(10, len(win_probs))
    for i in range(len(win_probs)):
        start_idx = max(0, i - window_size + 1)
        window = win_probs[start_idx:i+1]
        if len(window) >= 2:
            rolling_std.append(np.std(window))
        else:
            rolling_std.append(0.0)

    return differences, rolling_std


def plot_convergence_analysis(csv_file: str, output_prefix: str = "convergence_analysis"):
    """
    Create convergence analysis plots.

    Args:
        csv_file: Path to CSV file with convergence data
        output_prefix: Prefix for output plot files
    """
    print(f"Loading data from: {csv_file}")

    # Load data
    simulations, win_probs, timestamps = load_convergence_data(csv_file)

    if len(simulations) == 0:
        print("No data found in CSV file")
        return

    # Calculate metrics
    differences, rolling_std = calculate_convergence_metrics(win_probs)

    print(f"Loaded {len(simulations)} data points")
    print(".6f")
    print(".6f")
    print()

    # Create figure with subplots
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Monte Carlo Simulation Convergence Analysis', fontsize=16)

    # Plot 1: Win Probability vs Simulations
    ax1.plot(simulations, win_probs, 'b-', linewidth=2, alpha=0.7)
    ax1.plot(simulations, win_probs, 'ro', markersize=3, alpha=0.5)
    ax1.set_xlabel('Number of Simulations')
    ax1.set_ylabel('Win Probability')
    ax1.set_title('Win Probability vs Simulation Count')
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(max(0, min(win_probs) - 0.01), min(1, max(win_probs) + 0.01))

    # Plot 2: Difference from Final Value vs Simulations
    ax2.plot(simulations, differences, 'g-', linewidth=2)
    ax2.set_xlabel('Number of Simulations')
    ax2.set_ylabel('Absolute Difference from Final Value')
    ax2.set_title('Convergence: |Current - Final| vs Simulations')
    ax2.set_yscale('log')
    ax2.grid(True, alpha=0.3)

    # Plot 3: Rolling Standard Deviation vs Simulations
    ax3.plot(simulations, rolling_std, 'm-', linewidth=2)
    ax3.set_xlabel('Number of Simulations')
    ax3.set_ylabel('Rolling Std Dev (last 10 points)')
    ax3.set_title('Stability: Rolling Standard Deviation')
    ax3.set_yscale('log')
    ax3.grid(True, alpha=0.3)

    # Plot 4: Win Probability vs Time
    ax4.plot(timestamps, win_probs, 'c-', linewidth=2, alpha=0.7)
    ax4.plot(timestamps, win_probs, 'bo', markersize=3, alpha=0.5)
    ax4.set_xlabel('Time (seconds)')
    ax4.set_ylabel('Win Probability')
    ax4.set_title('Win Probability vs Time')
    ax4.grid(True, alpha=0.3)
    ax4.set_ylim(max(0, min(win_probs) - 0.01), min(1, max(win_probs) + 0.01))

    plt.tight_layout()

    # Save plots
    plot_file = f"{output_prefix}.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"Plots saved to: {plot_file}")

    # Also save as PDF for higher quality
    pdf_file = f"{output_prefix}.pdf"
    plt.savefig(pdf_file, bbox_inches='tight')
    print(f"PDF saved to: {pdf_file}")

    plt.show()

    # Print convergence analysis
    print("\n=== Convergence Analysis ===")

    # Find when difference drops below certain thresholds
    thresholds = [0.01, 0.005, 0.001, 0.0005, 0.0001]
    for threshold in thresholds:
        converged_at = None
        for i, diff in enumerate(differences):
            if diff < threshold:
                converged_at = simulations[i]
                break
        if converged_at:
            print("6d")
        else:
            print("6d")

    # Calculate rate of convergence (how fast difference decreases)
    if len(differences) > 100:
        early_diff = np.mean(differences[:100])
        late_diff = np.mean(differences[-100:])
        improvement_factor = early_diff / late_diff if late_diff > 0 else float('inf')
        print(".1f")

    print(f"\nFinal win probability: {win_probs[-1]:.6f}")
    print(f"Total simulations: {simulations[-1]}")
    print(f"Total time: {timestamps[-1]:.1f} seconds")


def analyze_multiple_csvs(csv_files: List[str], labels: List[str], output_prefix: str = "multi_convergence"):
    """
    Analyze and compare multiple convergence CSV files.

    Args:
        csv_files: List of CSV files to compare
        labels: Labels for each CSV file
        output_prefix: Prefix for output files
    """
    if len(csv_files) != len(labels):
        print("Error: Number of CSV files must match number of labels")
        return

    plt.figure(figsize=(12, 8))

    colors = ['blue', 'red', 'green', 'orange', 'purple', 'brown']

    for i, (csv_file, label) in enumerate(zip(csv_files, labels)):
        try:
            simulations, win_probs, _ = load_convergence_data(csv_file)
            color = colors[i % len(colors)]

            plt.plot(simulations, win_probs, color=color, linewidth=2, label=label, alpha=0.7)
            plt.plot(simulations, win_probs, color=color, marker='o', markersize=2, alpha=0.3)

        except Exception as e:
            print(f"Error loading {csv_file}: {e}")

    plt.xlabel('Number of Simulations')
    plt.ylabel('Win Probability')
    plt.title('Convergence Comparison: Multiple Hand Matchups')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1)

    plt.tight_layout()
    plt.savefig(f"{output_prefix}.png", dpi=300, bbox_inches='tight')
    plt.savefig(f"{output_prefix}.pdf", bbox_inches='tight')
    print(f"Comparison plot saved to: {output_prefix}.png")

    plt.show()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python simulation_analysis.py <csv_file> [output_prefix]")
        print("Or: python simulation_analysis.py --compare file1.csv file2.csv --labels label1 label2")
        sys.exit(1)

    if sys.argv[1] == "--compare":
        # Compare multiple files
        csv_files = []
        labels = []
        i = 2
        while i < len(sys.argv) and sys.argv[i] != "--labels":
            csv_files.append(sys.argv[i])
            i += 1

        if i < len(sys.argv) and sys.argv[i] == "--labels":
            i += 1
            while i < len(sys.argv):
                labels.append(sys.argv[i])
                i += 1

        if len(labels) == 0:
            labels = [f"File {i+1}" for i in range(len(csv_files))]

        analyze_multiple_csvs(csv_files, labels)
    else:
        # Analyze single file
        csv_file = sys.argv[1]
        output_prefix = sys.argv[2] if len(sys.argv) > 2 else "convergence_analysis"

        if not os.path.exists(csv_file):
            print(f"Error: CSV file '{csv_file}' not found")
            sys.exit(1)

        plot_convergence_analysis(csv_file, output_prefix)